@local = http://[::1]:5173
@slug=configs
@token=

###
GET {{local}}/api/{{slug}}?name=main
###
GET {{local}}/api/{{slug}}

###
GET {{local}}/api/{{slug}}?q=roles

###
POST {{local}}/api/{{slug}}
Content-Type: application/json

{
   "name": "roles",
   "label": "public",
   "value": "public"
}

###
PATCH {{local}}/api/{{slug}}/65c9bf1d115f1502dfc227a4
Content-Type: application/json

{
   "name": "methods",
   "label": "DELETE",
   "value": "DELETE"
}

###
DELETE {{local}}/api/{{slug}}/65ca26d03577244c7b71504d
