# @local = http://[::1]:5173
@local=http://localhost:5173
@slug=options
@token=

###
GET {{local}}/api/{{slug}}/names
###
GET {{local}}/api/{{slug}}

###
GET {{local}}/api/{{slug}}?page=0&size=21&sort_by=name

###
GET {{local}}/api/{{slug}}?name=colTypes

###
POST {{local}}/api/{{slug}}
Content-Type: application/json

{
   "name": "schemaTypes",
   "label": "boolean",
   "value": "boolean",
   "active": true
}

###
PATCH {{local}}/api/{{slug}}/65c9bf1d115f1502dfc227a4
Content-Type: application/json

{
   "name": "methods",
   "label": "DELETE",
   "value": "DELETE"
}

###
DELETE {{local}}/api/{{slug}}/65c9b7f0115f1502dfc2279e
